apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 3
    selector:
        matchLabels:
            app: paymentservice
    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
            - name: hipster-paymentservice
              image: zeph1rrinc/hipster-paymentservice:v0.0.2
              ports:
                  - containerPort: 34855
              env:
                  - name: PORT
                    value: "34855"
